### ISSUE TITLE
NuxtJS configuration file may be TypeScript

### ISSUE THREAD

**Issue by JamesMGreene** [paper-spa/configure-pages#10]
The NuxtJS documentation frequently suggests, as do their example applications, to use TypeScript. As such, they include support for a TypeScript based configuration file, `nuxt.config.ts`, instead of our currently targeted `nuxt.config.js`.

We should add support for both, apparently? 🤦🏻‍♂️

**Comment by TooManyBees** [comment]
This also means that the suggested workflows should be typescript aware, which means

1. We must be able to identify Next/Nuxt/Gatsby with a `.ts` extension on their config files
   * We also may want to submit a PR to Scout to add this support
2. The starter workflows may need to use a different build command, like `tsc` (if a package.json script named "build" doesn't exist)
